version: '3'
services:
 mysql-factoryService:
    image: mysql:8
    container_name: mysql-factoryService
    networks:
      - microservice
    volumes:
      - ./mysql-factory:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=shadow
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=factory_service 

 mysql-productService:
    image: mysql:8
    container_name: mysql-productService
    networks:
      - microservice
    volumes:
      - ./mysql-product:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=shadow
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=product_service

 api-gatewayService:
    image: api-gateway-service
    container_name: api-gatewayService
    networks:
      - microservice
    ports:
      - "8083:8083"
    environment:
      - spring.profiles.active=docker
    depends_on:
      - serviceDiscovery

 serviceDiscovery:
    image: discovery-service
    container_name: serviceDiscovery
    networks:
      - microservice
    ports:
      - "8761:8761"

 factory-service:
    image: factory-service
    container_name: factory-service
    networks:
      - microservice
    ports:
      - "8001:8001"
    environment:
      - spring.profiles.active=docker
    depends_on:
      - mysql-factoryService
      - serviceDiscovery

 product-service:
    image: product-service
    container_name: product-service
    networks:
      - microservice
    ports:
      - "8002:8002"
    environment:
      - spring.profiles.active=docker
    depends_on:
      - mysql-productService
      - serviceDiscovery
 

networks:
  microservice:

  