apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql2-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/data/mysql2"
