apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql2-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mysql2/data"
