apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql1-pvc
spec:
  resources:
    requests:
      storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  volumeName: mysql1-pv
