apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql1-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mysql1/data"
